### ISSUE TITLE
Enable automatic firmware build

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/NAT-TestFirmware#1]

**Comment by coderbyheart** [comment]
[Current Firmware Build](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4515688/merged.zip)

**Comment by PascalPickel** [comment]
[merged.zip](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4515871/merged.zip)

**Comment by boundlesscalm** [comment]
[merged.zip](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4516003/merged.zip)

**Comment by PascalPickel** [comment]
[Current Firmware Build](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4522270/merged.zip)

**Comment by PascalPickel** [comment]
[Current Firmware Build](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4539912/merged.zip)

**Comment by boundlesscalm** [comment]
[Current Firmware Build](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4543633/merged.zip)

**Comment by boundlesscalm** [comment]
[Current Firmware Build](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4544568/merged.zip)
