### ISSUE TITLE
Add configuration of NAT-TestFirmware through UART Shell

### ISSUE THREAD

**Issue by jhn-nordic** [NordicSemiconductor/NAT-TestFirmware#11]
To improve usability of the NAT-TestFirmware it should have the possiblity to be configured by UART shell.

_**By default it can start running the tests automatically from boot as it does today**_, but the following commands should be added to the shell.

```
stop_running_test

udp_test configure initial_timeout _number_ //1 is default?
udp_test start

tcp_test configure initial_timeout _number_ //hardcoded 200 in source
tcp_test configure timout_multiplier _number_  //hardcoded 1.5 in source
tcp_test start

network mode set  _string_ //(LTE-M or NB-IOT)
network mode get //returns LTE-M or NB-IOT
```

**Comment by coderbyheart** [comment]
@jhn-nordic can you review https://github.com/NordicSemiconductor/NAT-TestFirmware/pull/21?
