### ISSUE TITLE
Reset power saving settings in modem before running tests

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/NAT-TestFirmware#18]
Settings like eDRX are preserved in the modem flash and might be present from a previous app run. These need to be reset before running the tests.

@jtguggedal will provide the AT commands to achieve this.

**Comment by jtguggedal** [comment]
The LTE link controller can be used to disable both PSM and eDRX before connecting to the network:

```
lte_lc_psm_req(false);
lte_lc_edrx_req(false);
```
