### ISSUE TITLE
Give feedback in UI that system is working as expected

### ISSUE THREAD

**Issue by jhn-nordic** [NordicSemiconductor/NAT-TestFirmware#2]
During TCP tests the intervals can get quite long, and it can happen that i.e. the terminal is freezing but you really do not know.

I suggest adding something like this https://stackoverflow.com/questions/4995733/how-to-create-a-spinning-command-line-cursor in the uart output and use the leds to show if it is still running or it has completed

**Comment by boundlesscalm** [comment]
90239e9

**Comment by coderbyheart** [comment]
```
Waiting - %f seconds
Waiting - %f seconds
```
is not really helpful.

**Comment by coderbyheart** [comment]
Feedback is given every 5 seconds, should be 60.

**Comment by boundlesscalm** [comment]
Was caused by wrong hex being uploaded. Functional now.
